;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;; 30 x 18

inhook 3
tuck - f30 3
tuck - f28 3
tuck - f26 3
tuck - f24 3
tuck - f22 3
tuck - f20 3
tuck - f18 3
tuck - f16 3
tuck - f14 3
tuck - f12 3
tuck - f10 3
tuck - f8 3
tuck - f6 3
tuck - f4 3
tuck - f2 3
tuck + f1 3
tuck + f3 3
tuck + f5 3
tuck + f7 3
tuck + f9 3
tuck + f11 3
tuck + f13 3
tuck + f15 3
tuck + f17 3
tuck + f19 3
tuck + f21 3
tuck + f23 3
tuck + f25 3
tuck + f27 3
tuck + f29 3
releasehook 3

;row 1

knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3

;row 2

knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit + f21 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + f28 3
knit + f29 3
knit + f30 3

;row 3

knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3

;row 4

knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit + f21 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + f28 3
knit + f29 3
knit + f30 3

;row 5

knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3

;row 6
;pattern begins

inhook 1
knit + f1 3
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 3
knit + f6 1
knit + f7 3
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 3
knit + f12 1
knit + f13 3
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 3
knit + f18 1
knit + f19 3
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 3
knit + f24 1
knit + f25 3
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 3
knit + f30 3

;row 7

knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 1
knit - f26 3
knit - f25 1
knit - f24 3
knit - f23 1
knit - f22 3
knit - f21 1
knit - f20 3
knit - f19 1
knit - f18 3
knit - f17 1
knit - f16 3
knit - f15 1
knit - f14 3
knit - f13 1
knit - f12 3
knit - f11 1
knit - f10 3
knit - f9 1
knit - f8 3
knit - f7 1
knit - f6 3
knit - f5 1
knit - f4 3
knit - f3 1
knit - f2 3
knit - f1 3

;row 8

knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 1
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 1
knit + f9 3
knit + f10 1
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 1
knit + f15 3
knit + f16 1
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 1
knit + f21 3
knit + f22 1
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 1
knit + f27 3
knit + f28 3
knit + f29 3
knit + f30 3

;row 9

knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 1
knit - f26 3
knit - f25 3
knit - f24 1
knit - f23 3
knit - f22 3
knit - f21 1
knit - f20 3
knit - f19 3
knit - f18 1
knit - f17 3
knit - f16 3
knit - f15 1
knit - f14 3
knit - f13 3
knit - f12 1
knit - f11 3
knit - f10 3
knit - f9 1
knit - f8 3
knit - f7 3
knit - f6 1
knit - f5 3
knit - f4 3
knit - f3 1
knit - f2 3
knit - f1 3

;row 10

knit + f1 3
knit + f2 3
knit + f3 1
knit + f4 3
knit + f5 3
knit + f6 1
knit + f7 3
knit + f8 3
knit + f9 1
knit + f10 3
knit + f11 3
knit + f12 1
knit + f13 3
knit + f14 3
knit + f15 1
knit + f16 3
knit + f17 3
knit + f18 1
knit + f19 3
knit + f20 3
knit + f21 1
knit + f22 3
knit + f23 3
knit + f24 1
knit + f25 3
knit + f26 3
knit + f27 1
knit + f28 3
knit + f29 3
knit + f30 3

;row 11

knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 1
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 1
knit - f21 3
knit - f20 1
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 1
knit - f15 3
knit - f14 1
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 1
knit - f9 3
knit - f8 1
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 1
knit - f3 3
knit - f2 3
knit - f1 3

;row 12

knit + f1 3
knit + f2 3
knit + f3 1
knit + f4 3
knit + f5 1
knit + f6 3
knit + f7 1
knit + f8 3
knit + f9 1
knit + f10 3
knit + f11 1
knit + f12 3
knit + f13 1
knit + f14 3
knit + f15 1
knit + f16 3
knit + f17 1
knit + f18 3
knit + f19 1
knit + f20 3
knit + f21 1
knit + f22 3
knit + f23 1
knit + f24 3
knit + f25 1
knit + f26 3
knit + f27 1
knit + f28 3
knit + f29 3
knit + f30 3

;row 13

knit - f30 3
knit - f29 3
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 3
knit - f24 1
knit - f23 3
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 3
knit - f18 1
knit - f17 3
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 3
knit - f12 1
knit - f11 3
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 3
knit - f6 1
knit - f5 3
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 3
releasehook 1
;pattern end

;row 14


knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit + f21 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + f28 3
knit + f29 3
knit + f30 3

;row 15

knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3

;row 16

knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit + f21 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + f28 3
knit + f29 3
knit + f30 3

;row 17

knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3

;row 18

knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit + f21 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + f28 3
knit + f29 3
knit + f30 3

outhook 1
outhook 3


